### ISSUE TITLE
Installing on Windows 

### ISSUE THREAD

**Issue by cklat** [mskimm/tensorflow-scala#1]
Is the installation process still up-to-date and do you know if I can also install it on a windows machine?
I tried to use cygwin64 for the installation and followed the commands of building the native TensorFlow Library. 

When executing the sbt compileNative command, I get the following output:

> $ sbt compileNative
[info] Loading project definition from C:\TensorFlow\tensorflow-scala\project
Missing bintray credentials C:\Users\XXX\.bintray\.credentials. Some bintray features depend on this.
[info] Set current project to tensorflow-scala (in build file:/C:/TensorFlow/tensorflow-scala/)
error: pathspec 'v0.10.0' did not match any file(s) known to git.
mv: cannot stat 'tensorflow/bazel-bin/tensorflow/jna/libtensorflow.so': No such file or directory

Do you might know how to resolve this problem? Bazel is installed however highly experimental for Windows as stated on the official TensorFlow homepage

**Comment by em3s** [comment]
Sorry, this issue is also shown in my osx machine. Could you try

```
rm -rf tensorflow
git submodule init
git submodule update
#then
sbt compileNative
```
.

As you see, This problem is that submodule is not initialized. (I will update the README.md)

By the way, I plan to use the pre-built binary of `pip` then no `sbt compileNative` is required.

Thanks

**Comment by cklat** [comment]
Still having difficulties even after executing your suggested code:

> $ sbt compileNative
[info] Loading project definition from C:\TensorFlow\tensorflow-scala\project
Missing bintray credentials C:\Users\XXX\.bintray\.credentials. Some bintray features depend on this.
[info] Set current project to tensorflow-scala (in build file:/C:/TensorFlow/tensorflow-scala/)
HEAD is now at c715c31... Merge pull request #4284 from caisq/r0.10-fixes
mv: cannot stat 'tensorflow/bazel-bin/tensorflow/jna/libtensorflow.so': No such file or directory

**Comment by em3s** [comment]
@cklat How about use TensorFlow Java API in https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/package-summary

It contains not only Windows Native Library but also more intuitive for TensorFlow users.

**Comment by em3s** [comment]
I Changed the objective of this project to `Serving TensorFlow Models` with Scala. From now on this project uses Java API provided by TensorFlow which supports Windows as well. 

If `sbt` is installed on your system, the following commands will work

```
$ git clone https://github.com/mskimm/tensorflow-scala.git
$ cd tensorflow-scala
$ (cd model; sh download.sh) # download inception-v3
$ sbt "run-main tensorflow.TensorFlowExample cropped_panda.jpg"
or
$ sbt "run-main tensorflow.TensorFlowExample /path/to/jpg/image"
```
